version: '3.3'
services:
  drop-api:
    container_name: 'drop-api'
    build: '.'
    ports:
      - '8080:8080' #CRUD API
      - '4040:4040' #DEBUG API
    depends_on:
      - 'mongo'
  # web:
  #   container_name: 'web'
  #   image: 'nginx:latest'
  #   ports:
  #     - '8081:80'
  #   volumes:
  #     - './web:/usr/share/nginx/html'
  #   depends_on:
  #     - 'api'
  mongo:
    image: 'mongo:4.4.5'
    container_name: 'mongo'
    ports:
      - '27100:27017'