// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: protodrop/protodrop.proto

package protodrop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeSlot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID         string `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
}

func (x *TimeSlot) Reset() {
	*x = TimeSlot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodrop_protodrop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlot) ProtoMessage() {}

func (x *TimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_protodrop_protodrop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlot.ProtoReflect.Descriptor instead.
func (*TimeSlot) Descriptor() ([]byte, []int) {
	return file_protodrop_protodrop_proto_rawDescGZIP(), []int{0}
}

func (x *TimeSlot) GetUID() string {
	if x != nil {
		return x.UID
	}
	return ""
}

func (x *TimeSlot) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TimeSlot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TimeSlotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TimeSlot *TimeSlot `protobuf:"bytes,2,opt,name=timeSlot,proto3" json:"timeSlot,omitempty"`
}

func (x *TimeSlotResponse) Reset() {
	*x = TimeSlotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodrop_protodrop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlotResponse) ProtoMessage() {}

func (x *TimeSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protodrop_protodrop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlotResponse.ProtoReflect.Descriptor instead.
func (*TimeSlotResponse) Descriptor() ([]byte, []int) {
	return file_protodrop_protodrop_proto_rawDescGZIP(), []int{1}
}

func (x *TimeSlotResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TimeSlotResponse) GetTimeSlot() *TimeSlot {
	if x != nil {
		return x.TimeSlot
	}
	return nil
}

// The request message containing the listing ID to search for
type GetTimeSlotByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTimeSlotByIdRequest) Reset() {
	*x = GetTimeSlotByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protodrop_protodrop_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimeSlotByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeSlotByIdRequest) ProtoMessage() {}

func (x *GetTimeSlotByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protodrop_protodrop_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeSlotByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTimeSlotByIdRequest) Descriptor() ([]byte, []int) {
	return file_protodrop_protodrop_proto_rawDescGZIP(), []int{2}
}

func (x *GetTimeSlotByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_protodrop_protodrop_proto protoreflect.FileDescriptor

var file_protodrop_protodrop_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x72, 0x6f, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x64, 0x72, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x64, 0x72, 0x6f, 0x70, 0x22, 0x54, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c,
	0x6f, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x53, 0x0a, 0x10,
	0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x2f, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x72, 0x6f, 0x70, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f,
	0x74, 0x22, 0x28, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x66, 0x0a, 0x0f, 0x54,
	0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x42, 0x79, 0x49,
	0x64, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x72, 0x6f, 0x70, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x72, 0x6f, 0x70,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6e, 0x65, 0x78, 0x74, 0x77, 0x61, 0x76, 0x65, 0x64, 0x65, 0x76, 0x73, 0x2f, 0x64,
	0x72, 0x6f, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x72, 0x6f, 0x70, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protodrop_protodrop_proto_rawDescOnce sync.Once
	file_protodrop_protodrop_proto_rawDescData = file_protodrop_protodrop_proto_rawDesc
)

func file_protodrop_protodrop_proto_rawDescGZIP() []byte {
	file_protodrop_protodrop_proto_rawDescOnce.Do(func() {
		file_protodrop_protodrop_proto_rawDescData = protoimpl.X.CompressGZIP(file_protodrop_protodrop_proto_rawDescData)
	})
	return file_protodrop_protodrop_proto_rawDescData
}

var file_protodrop_protodrop_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protodrop_protodrop_proto_goTypes = []interface{}{
	(*TimeSlot)(nil),               // 0: protodrop.TimeSlot
	(*TimeSlotResponse)(nil),       // 1: protodrop.TimeSlotResponse
	(*GetTimeSlotByIdRequest)(nil), // 2: protodrop.GetTimeSlotByIdRequest
}
var file_protodrop_protodrop_proto_depIdxs = []int32{
	0, // 0: protodrop.TimeSlotResponse.timeSlot:type_name -> protodrop.TimeSlot
	2, // 1: protodrop.TimeSlotService.GetTimeSlotById:input_type -> protodrop.GetTimeSlotByIdRequest
	1, // 2: protodrop.TimeSlotService.GetTimeSlotById:output_type -> protodrop.TimeSlotResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protodrop_protodrop_proto_init() }
func file_protodrop_protodrop_proto_init() {
	if File_protodrop_protodrop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protodrop_protodrop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSlot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protodrop_protodrop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeSlotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protodrop_protodrop_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTimeSlotByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protodrop_protodrop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protodrop_protodrop_proto_goTypes,
		DependencyIndexes: file_protodrop_protodrop_proto_depIdxs,
		MessageInfos:      file_protodrop_protodrop_proto_msgTypes,
	}.Build()
	File_protodrop_protodrop_proto = out.File
	file_protodrop_protodrop_proto_rawDesc = nil
	file_protodrop_protodrop_proto_goTypes = nil
	file_protodrop_protodrop_proto_depIdxs = nil
}
